# Generated by Django 4.0.1 on 2022-04-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_review_rename_owner_comment_commenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
